/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 charter.gltf 
Author: Priichu (https://sketchfab.com/priichu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nijisanjien-chibi-finana-and-luca-0b20e640963c4ad480245ea089cf561c
Title: NijisanjiEN: Chibi Finana and Luca
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Charter(props) {
  const { scene } = useGLTF("/charter.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <group position={[0.547, 0, 0]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials["Luca_Diffuse.002"]}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_8.geometry}
          material={materials.Luca_Diffuse}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_10.geometry}
          material={materials["Luca_Diffuse.001"]}
          skeleton={nodes.Object_10.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials["Luca_Diffuse.002"]}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_13.geometry}
          material={materials["Luca_Diffuse.001"]}
          skeleton={nodes.Object_13.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_14.geometry}
          material={materials["Luca_Diffuse.002"]}
          skeleton={nodes.Object_14.skeleton}
        />
      </group>
      <group position={[-0.633, 0, 0]} scale={0.58}>
        <primitive object={nodes.GLTF_created_1_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_88.geometry}
          material={materials.Finana}
          skeleton={nodes.Object_88.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/charter.gltf");
